# Generated by Django 5.2.16 on 2026-08-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=80)),
                ('interests', models.JSONField(default=list)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('operating_days', models.JSONField(default=list)),
                ('visit_minutes', models.PositiveIntegerField(default=90)),
                ('entrance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activities', models.JSONField(default=list)),
                ('accessibility', models.CharField(blank=True, max_length=255)),
                ('contact_information', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('transportation_options', models.JSONField(default=list)),
                ('safety_reminders', models.JSONField(default=list)),
                ('recommended_companions', models.JSONField(default=list)),
                ('advisory', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(default='Dalaguete', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('travel_date', models.DateField()),
                ('preferences', models.JSONField(default=dict)),
                ('itinerary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
