# Generated by Django 5.2.16 on 2026-08-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_remove_demo_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='entrance_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='destination',
            name='visit_minutes',
            field=models.PositiveIntegerField(),
        ),
    ]
