# Generated by Django 5.2.16 on 2026-08-05 12:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_destination_availability_and_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('home_location', models.CharField(blank=True, max_length=180)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('preferred_pace', models.CharField(choices=[('relaxed', 'Relaxed'), ('balanced', 'Balanced'), ('fast', 'Fast-paced')], default='balanced', max_length=20)),
                ('preferred_transportation', models.CharField(choices=[('public', 'Public transit'), ('motorcycle', 'Motorcycle taxi'), ('private', 'Private vehicle'), ('walking', 'Walking')], default='public', max_length=20)),
                ('preferred_language', models.CharField(choices=[('English', 'English'), ('Filipino', 'Filipino'), ('Cebuano', 'Cebuano')], default='English', max_length=20)),
                ('accessibility_needs', models.CharField(blank=True, max_length=255)),
                ('typical_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=1200)),
                ('suggestion', models.TextField(blank=True, max_length=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_reviews', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='itineraries.destination')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('destination', 'author'), name='unique_tourist_destination_review')],
            },
        ),
    ]
