# Generated by Django 5.2.16 on 2026-08-05 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0007_touristprofile_destinationreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Travel Osmena', max_length=80)),
                ('tagline', models.CharField(default='Your local escape, thoughtfully planned.', max_length=180)),
                ('organization_name', models.CharField(default='Sergio Osmeña Sr. Tourism Office', max_length=180)),
                ('municipality_name', models.CharField(default='Sergio Osmeña Sr., Zamboanga del Norte', max_length=180)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=40)),
                ('logo', models.FileField(blank=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
