# Generated by Django 5.2.16 on 2026-08-05 13:31

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0008_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristprofile',
            name='available_end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='available_start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='preferred_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='starting_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='touristprofile',
            name='traveler_type',
            field=models.CharField(choices=[('solo', 'Solo traveler'), ('couple', 'Couple'), ('family', 'Family'), ('friends', 'Friend group'), ('senior', 'Senior traveler')], default='solo', max_length=20),
        ),
    ]
