# Generated by Django 5.2.5 on 2026-09-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0009_touristprofile_available_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='barangay_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='destination',
            name='municipality_code',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='destination',
            name='province_code',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
