# Generated by Django 5.2.5 on 2026-09-28 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0010_destination_barangay_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditinerary',
            name='signature',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='saveditinerary',
            constraint=models.UniqueConstraint(fields=('owner', 'signature'), name='unique_owner_itinerary_signature'),
        ),
    ]
